### ISSUE TITLE
Make it possible to use Aptabase with any programming language

### ISSUE THREAD

**Issue by LorenDB** [aptabase/aptabase#101]
It would be awesome if I could use Aptabase in any programming language (C++ is the big one for me). To that end, I'd like to see either (a) a C or C++ API that can be wrapped into other languages, or (b) a well-documented REST API that lets you just roll your own client.

**Comment by cristipufu** [comment]
Hi @LorenDB!

We accept contributions, I can create a new C++ repository for the SDK and give you permissions to push code/maintain it.
At this moment, the SDKs are pretty straight-forward, you just have to make an API call which is documented here: https://github.com/aptabase/aptabase/wiki/How-to-build-your-own-SDK

What is important is to avoid blocking the main thread when sending the events (we need to send them asynchronously) and it would be nice if the SDK supported persistence (in case of app crashes we don't lose events)

**Comment by cristipufu** [comment]
Let me know how it goes please :)
