### ISSUE TITLE
Aptabase not sending event on First Page Load for Next.js Page Router

### ISSUE THREAD

**Issue by faraasat** [aptabase/aptabase#108]
I have integrated Aptabase into my app https://gpacalculate.vercel.app/ and repo https://github.com/faraasat/gpa-calc.

In production, the issue is that it does not send the event on the first page load but sends the event when we route it to another page.

In development (debug), it sends one event on the first page load and two events when we route to another page.

I have used it in my other Next.js App with App Router, and it works fine there.

```
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 23.6.0
  Available memory (MB): 8192
  Available CPU cores: 8
Binaries:
  Node: 22.3.0
  npm: 10.8.1
  Yarn: N/A
  pnpm: 9.10.0
Relevant Packages:
  next: 14.2.11 // Latest available version is detected (14.2.11).
  eslint-config-next: 12.1.0
  react: 18.3.1
  react-dom: 18.3.1
  typescript: 4.6.2
Next.js Config:
  output: N/A
```

**Comment by ivnbogdan** [comment]
Thank you for reporting this.
I have reproduced the issue and am working on a fix.

Meanwhile a workaround -- that I saw you are already using in your repo -- is to call track on initialisation like this
```
useEffect(() => {
    trackEvent(...);
  }, [trackEvent]);
```

**Comment by faraasat** [comment]
One thing I want to request is that Aptabase does not calculate the session time and only adds the time if the user routes. I have also enabled vertical analytics in one of my apps, which shows whether a user is online or not.

Do you know if this capability will be added to the library? Should I create a new feature request?

**Comment by ivnbogdan** [comment]
> One thing I want to request is that Aptabase does not calculate the session time and only adds the time if the user routes. I have also enabled Vercel analytics in one of my apps, which shows whether a user is online or not.
> 
> Do you know if this capability will be added to the library? Should I create a new feature request?

It would be best to add a new ticket to track this feature request.

However I'm not entirely sure I understand the request. Aptabase currently uses the same `sessionId` between trackEvents. If more than 1h is elapsed between 2 consecutive trackEvents, then the `sessionId` is reset to a new value.
Besides this, each trackEvent has attached a timestamp of that single event.
Aptabase is a privacy-first analytics solution, which means are not identifying each user in any other way, besides this `sessionId` which is randomly generated like described above. Unlike other analytics solutions, we don't identify each user persistently.

**Comment by ivnbogdan** [comment]
> What I mean is if the user visits the `Home Page`, time is not recorded until he moves to any other page. For example, if a user visits a page and then closes the window after 3 min without going to another page, it will show 0s for the event.
> 
> ![image](https://private-user-images.githubusercontent.com/63093876/368878897-ac7b3909-fcbd-484f-9859-b0d2ce3aeac4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzAyMzcsIm5iZiI6MTcyNjcyOTkzNywicGF0aCI6Ii82MzA5Mzg3Ni8zNjg4Nzg4OTctYWM3YjM5MDktZmNiZC00ODRmLTk4NTktYjBkMmNlM2FlYWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA3MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjOWYzNDg5MjQ0Nzk0ZjhhNGVmNThlYWQyMDc5ZmVhY2QzNWNkYWExNTRkNjUyOGJmN2JlMmM3YTViMDQ1MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bI9jCOI2YnhCaJuUL-ZEkQT4PFkaOeznjesKOCk3V4g)
> 
> As shown in the above screenshot, I can't find out how much time the user has spent on this page.

Aptabase does not track any events by default -- like tracking navigation between pages.
In your above example, since there was exactly 1 event tracked in that session, we will show that 0s time.

To achieve the behaviour you described, your calling code should call a new `trackEvent` for each page navigation, and one more when the application is closed -- which may be identified with https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event `hidden` value.

We intentionally avoided tracking events from inside the framework so that the client has full control of what gets sent.
