### ISSUE TITLE
❌ "No data" after every reload - Even if there is data [self-host]

### ISSUE THREAD

**Issue by musiolmarco** [aptabase/aptabase#112]
Hey, we are using Aptabase now to test if it is suitable for us (self hosted). The Flutter Package works quite well and all events are tracked. However, the dashboard is often very buggy. 

I'll attach a few screenshots of what it looks like after each page reload. There is data available, but it only loads after each reload and there are always other fields “No Data”, although there is actually data available. Does anyone else have this problem? I've had this for quite some time now, once locally and once on our servers.
<img width="1084" alt="Screenshot 2024-10-14 at 17 50 46" src="https://github.com/user-attachments/assets/eaffa2dc-327b-46ca-bf98-92028558c3ca">

<img width="1097" alt="Screenshot 2024-10-15 at 10 33 40" src="https://github.com/user-attachments/assets/2fdc9101-e744-4230-a865-337add2784fa">

<img width="1097" alt="Screenshot 2024-10-15 at 10 33 47" src="https://github.com/user-attachments/assets/bfb4cde1-8274-4aee-b1d7-86eede0320d0">

<img width="1112" alt="Screenshot 2024-10-15 at 10 34 05" src="https://github.com/user-attachments/assets/d9a33693-4a0c-42ee-8463-cb9963eb990b">

**Comment by ivnbogdan** [comment]
Hello @musiolmarco , thanks for letting us know of this issue.

To clarify the scenario: this is happening for the self-hosted version, where you are serving the requests and front-end app from your own services?
Or have you seen this behaviour for our dashboards hosted on eu.aptabase.com or us.aptabase.com?

**Comment by musiolmarco** [comment]
I'm using Aptabase self hosted and the aptabase_flutter 0.4.0 package. I hosted Aptabase locally in my Docker to test it first. It worked so far, but I often had the described bug in the dashboard. I thought maybe it was because it runs slower locally, because I only work on my MacBook and the app/simulator in the background also takes away some performance.

That's why we hosted it on our production server again for testing yesterday and unfortunately exactly the same thing happens here. The data is there, but the dashboard overview always takes a little longer to load and sometimes some things are not loaded - i.e. “No Data”. When I reload, the values that previously had “No Data” are sometimes there, but then other data fields are no longer there.

It should also be mentioned that when I have it running locally and the bug occurs, I simply restarted the container and then everything worked fine for a few minutes, but after a few minutes the same thing happened.

-----

I use the Brave Browser and also already disabled the "Brave shield" (Ad blocker). 
I just checked again, everything is working right now. I'll wait until the bug comes back and then try another browser, maybe that will help 🙏

**Comment by ivnbogdan** [comment]
When it happens you might want to collect a `.har` file so we can take a look.
Additionally it's not clear to me if the issue you are describing is a front end or a back end problem.

When 'no data' is displayed, are there any failed Network requests? Or is everything working fine and are there any console errors?

**Comment by musiolmarco** [comment]
Sorry for the late response @ivnbogdan. 

I don't know why or what the problem was, but now that it's been live for a few days and a few more events have been tracked, everything seems to be working at the moment. If the error happens again, I'll get back to you with more information :)
