### ISSUE TITLE
Daily Active Users

### ISSUE THREAD

**Issue by goenning** [aptabase/aptabase#18]
Aptabase doesn't currently have a definition for "User ID" in its events due to privacy reasons as we don't want events and sessions to be linked to a user.

This means we can't calculate unique daily users and other metrics.

However we could apply something similar to what Plausible does with an automatic refreshed salt that is thrown away daily.

This would at least give us daily unique users, but not weekly/monthly.

**Comment by flutter-painter** [comment]
if you put web aside you could save a uniqueId per device and only count uniqueIds
if another account is used on the device to log in it does not matter, all you want is to know how many used it

**Comment by goenning** [comment]
I'm not sure what you mean by `only count uniqueIds`.

However, generating a unique id per device would be considered fingerprinting under some privacy laws such as GDPR. It's similar to what GA does with cookies.

**Comment by flutter-painter** [comment]
You are right, too bad. 

You could still complete the daily metric you had in mind by collecting those data (while remaining gdpr compliant) :
- appVersion
- operatingSystem
- numberOfProcessors

And getting a rough idea of the system computation power by running something like :

```dart
final t1 = DateTime.now();
        final list = Iterable<double>.generate(100000000, (i) => 100000000);
        for (var l in list) {
          l += 1 + 1;
        }
        final t2 = DateTime.now();
        final uniqueId = t2.difference(t1);
        final uuid = (uniqueId.inMilliseconds / 1000).round();
```

Would be also useful to get the **locale**,
I doubt it is considered "personnal information" but this neesd to double check.

What do you think ?

**Comment by goenning** [comment]
Yeah those properties would not be considered PII. The solution I have in place uses a combination of those + IP address + a strong cryptographic salt that changes daily. So we can get the DAU metric without any form of long term tracking.

I have the backend work done, just need to add the metrics to the frontend now.
