### ISSUE TITLE
Billing Usage Percentage - Minor Bug

### ISSUE THREAD

**Issue by Qfc9** [aptabase/aptabase#68]
Using the actual service, not the self-hosted stuff.

Very minor bug, as you can see it looks like the % for billing usage progress multiplication is off by a x10. 

<img width="843" alt="Screenshot 2023-12-31 at 12 13 00 PM" src="https://github.com/aptabase/aptabase/assets/5085587/2cd5551a-b3d6-48da-8ff6-a48b45a45d83">

**Comment by goenning** [comment]
This is fixed now, thanks for reporting it!
