### ISSUE TITLE
Add device model for Android analytics

### ISSUE THREAD

**Issue by roozbehzarei** [aptabase/aptabase#73]
Device model could be retrieved using the Build class in Android. Refer to [this article](https://www.geeksforgeeks.org/how-to-get-the-device-information-in-android/) for more information.

**Comment by roozbehzarei** [comment]
I see the following information are sent by the Kotlin SDK:
`timestamp`,  `sessionId`,  `eventName`, `systemProps`, `props`. Since `systemProps` holds the information related to the system, I can send a PR with `deviceModel` property added to the JSON response in case the website can process the data.

**Comment by goenning** [comment]
If you want to add that on a PR, I’m happy to merge it. The server will eventually support device model too, but until then it’ll simply ignore it

**Comment by roozbehzarei** [comment]
I assume the naming of JSON objects and properties are the same across all platforms? If so, what should be the property name for device model?

**Comment by goenning** [comment]
deviceModel seems like a good name to me 👍

**Comment by roozbehzarei** [comment]
PR: https://github.com/aptabase/aptabase-kotlin/pull/3

Added `deviceModel` to the `systemProps` property in the JSON object. Feel free to make contact if you need any additional information added in the future.

**Comment by goenning** [comment]
I actually wanted to ask if it’s possible to add a Kotlin/Android dependency directly from GitHub, without having to publish to Maven.

and if that’s a common thing to do. The current process to publish to Maven is very tedious

**Comment by roozbehzarei** [comment]
> I actually wanted to ask if it’s possible to add a Kotlin/Android dependency directly from GitHub, without having to publish to Maven.
> 
> and if that’s a common thing to do. The current process to publish to Maven is very tedious

It's possible and somewhat common. While the most popular libs are all on Maven, there are still many hosted on GitHub. Anyone who wants to import a library from GitHub should add an additional repository in their project and the process doesn't introduce any issues.

If you're interested in doing so, I can make the required changes to the library to make it happen.

**Comment by goenning** [comment]
Yeah let’s do that! :)

**Comment by roozbehzarei** [comment]
PR: https://github.com/aptabase/aptabase-kotlin/pull/4

Make sure to read the PR description before merging.

**Comment by goenning** [comment]
Thanks @roozbehzarei do I need to do anything on https://jitpack.io/ ?

**Comment by roozbehzarei** [comment]
Sure thing.
No, the process is automatic. Still, I will run a test as soon as the changes are merged to ensure everything works as expected.
