### ISSUE TITLE
Does @aptabase/web support nodejs?

### ISSUE THREAD

**Issue by 6174** [aptabase/aptabase#75]
First thanks for providing such cool tool for developers,  and I am new to use aptabase,  I have a nodejs + react based saas project. I already setup react sdk for aptabase to trace event. But I am confuse how to trace event in my nodejs layer? I searched the docs and issues list , no answer showed :-/

**Comment by goenning** [comment]
TLDR: Not currently, because it was initially designed for mobile/desktop apps. 

See this issue for more info https://github.com/aptabase/aptabase-js/issues/5
