### ISSUE TITLE
Website doesn't render correctly on Firefox

### ISSUE THREAD

**Issue by gilleslijnzaad** [aptabase/aptabase#84]
I wanted to read [the Apple App Privacy docs](https://aptabase.com/docs/apple-app-privacy) and the website didn't render correctly. This is what it looks like. I scrolled down a bit to show the text content; this isn't the actual top of the page. The top of the page only showed huge logos for Aptabase and GitHub.

![screenshot](https://github.com/aptabase/aptabase/assets/55486579/44cedf80-40a8-43a1-9620-9db5c31e26db)

This was on Firefox 125.0.3 on Windows 11. It worked properly when I tried it on Microsoft Edge 124.0.2478.67.

**Comment by AldeRoberge** [comment]
Same problem on Chrome and Windows 10 right now
![image](https://github.com/aptabase/aptabase/assets/4276275/e80f8089-a038-4b58-8c2b-59c3e1b1f6fa)

**Comment by goenning** [comment]
@AldeRoberge can you try something for me? Does it work ok private session without extensions?

**Comment by AldeRoberge** [comment]
Left = normal, right = private
![image](https://github.com/aptabase/aptabase/assets/4276275/d98a755f-51a1-4a8a-9a53-f3962e1213ae)
My bad, yeah it seems like it's because of an extension (adblocker probably), weird because it worked fine

**Comment by gilleslijnzaad** [comment]
Ah, for me it works when I disable uBlock Origin too. Thanks!
