### ISSUE TITLE
Maximum length of AppVersion and OSVersion

### ISSUE THREAD

**Issue by jakub-lat** [aptabase/aptabase#85]
Hi,

While integrating Aptabase into my Unity game, I encountered this error multiple times:

```
Failed to perform web request due to 400 and response body HTTP/1.1 400 Bad Request
```

After investigating the issue with mitmproxy, I found out that AppVersion has a maximum length of 20 and OSVersion - 30. 

![DiscordCanary_HFos6LfG7B](https://github.com/aptabase/aptabase/assets/43910288/4be2adf6-9cbb-4e79-92f6-8e13ca1155d3)
![image](https://github.com/aptabase/aptabase/assets/43910288/05b3eea5-3149-49a9-ae9e-8fa90585cc5f)

The AppVersion length restriction is not so bad, because I can always trim it on the client-side. But as for OSVersion on Linux, the Aptabase Unity SDK automatically sets it to something like `Linux 6.1 Debian GNU/Linux 12 64bit`, which is a bit too long - and there is no way to change it, except maybe forking the SDK and trimming it manually.

Could you increase max lengths of those to for example 50, or add a setting to adjust that per-project? It's really annoying. I can submit a PR if it's not an issue to increase those restrictions.

**Comment by cristipufu** [comment]
New limits:
- `AppVersion` Maximum Length: 50 characters
- `OSVersion` Maximum Length: 100 characters
