### ISSUE TITLE
Self hosted: SMTP configuration not working

### ISSUE THREAD

**Issue by dowmeister** [aptabase/aptabase#88]
Hello there,

trying to setup the self hosted docker container, i've encountered immediately a problem about sending email: using internally a mail trap like `mailpit` and the public SMTP i use in other applications.

Both cases, the UI hangs

![image](https://github.com/aptabase/aptabase/assets/518905/eebdb593-24d3-4463-8575-b60c004b6fac)

When using `mailpit` says the email has been sent but is not true, no emails received on other side.

Furthermore there is no relevant log entry in container logs.

```
SMTP_HOST: <my smtp server>
SMTP_PORT: 465
SMTP_USERNAME: <smtp account>
SMTP_PASSWORD:  <smtp password>
SMTP_FROM_ADDRESS: <smtp account> // an email too
```

Probably i'm messing with something :D

**Comment by dowmeister** [comment]
not maintained anymore?

**Comment by cristipufu** [comment]
@dowmeister this is an OSS project. Feel free to debug and contribute with a pull request if you find the issue

**Comment by dowmeister** [comment]
i was able to configure a new instance without SMTP dealing with hardcoded links and bugged behaviors.
when finally tracked the first event didn't found what I was looking for, probably the project is too young and I was expecting something more.
not interested in contributing, right now.
