### ISSUE TITLE
Total number of users per day (today/yesterday filters)

### ISSUE THREAD

**Issue by cristipufu** [aptabase/aptabase#90]
> i want know the total users per day.

The "last 24h" filters keeps changing the numbers through the day, so what i suggest is to add a filter for "today" and "yesterday". compiling the data from the beggining till the end of the day.

**Comment by cristipufu** [comment]
Related: https://github.com/aptabase/aptabase/pull/79

**Comment by ivnbogdan** [comment]
Implemented in https://github.com/aptabase/aptabase/pull/93

**Comment by glundgrenm** [comment]
@cristipufu hey cristi, thanks for the quick response here! Unfortanetly the data is being filtered using with the server time zone (UTC), so for me, in Brazil (-3h), the data comes from 9pm to 8:59pm, not 0h to 11:59pm.

**Comment by ivnbogdan** [comment]
> @cristipufu hey cristi, thanks for the quick response here! Unfortanetly the data is being filtered using with the server time zone (UTC), so for me, in Brazil (-3h), the data comes from 9pm to 8:59pm, not 0h to 11:59pm.

We'll come up with a fix shortly to prefer the local browser timezone when defining 'today' & 'yestarday'

**Comment by glundgrenm** [comment]
@ivnbogdan actually, i think this is impacting all the data, for example, using the "yesterday" filter, i got the same number as if i hover the mouse over yesterday on the "Last 7 days" chart.
